development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: myblog
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: myblog
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: myblog
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres